# 5.1.1 Relu 계층

렐루의 forward pass와 back propagation을 살펴보면 아래와 같다.

<p align="center"><img src="imgs/5-7s.png" width=600></p>

코드에서도 순방향은 그냥 구현하면 되고, 역방향은 x <= 0 일 경우에만 0으로 처리해주면 된다.

In [2]:
import numpy as np

class Relu:
    def __init__(self):
        self.mask = None # True or False

    def forward(self, x):
        self.mask = (x <= 0)
        print('mask:', self.mask)
        out = x.copy()
        out[self.mask] = 0
        print(out)

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        return dx

* mask 변수의 의미를 알고 갈 것
* backward에서 self.mask가 작동하기 때문에, 계산이 쉬워진다는 것도 알면 좋음

In [4]:
relu = Relu()

x = np.array([1.0, -2.0, -5.0, 10.0])
relu.forward(x)


mask: [False  True  True False]
[ 1.  0.  0. 10.]


array([ 1.,  0.,  0., 10.])

* 아래 예시에서는 편의상 backward에 x를 그대로 넣었다
* 하지만 실제 계산에서는, global loss로부터 계산된 배열이 들어간다.
* 그러니 값들은 그냥 참고용으로만 알아두자.

In [9]:
relu.backward(x)

array([ 1.,  0.,  0., 10.])

In [5]:
class Sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out

        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx