# 3.3.1 다차원배열

1차원 배열부터 구현해보자.

In [3]:
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)
print(A.ndim)       # 배열의 차원 수 확인
print(A.shape)      # 형상 확인
print(A.shape[0])   # 1번째 차원의 모양

[1 2 3 4]
1
(4,)
4


In [4]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(B.ndim)
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


* 2차원 배열은 행렬이라고 부른다. (Matrix)
* 가로는 행, 세로는 열이다. (row, column)

# 3.3.2 행렬의 곱

행렬의 곱은 np.dot으로 구현할 수 있다. elementwise가 아니라는 점을 기억하자.

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

print(A.shape, B.shape)
np.dot(A, B)

(2, 3) (3, 2)


array([[22, 28],
       [49, 64]])

행렬의 곱에서는 대응되는 차원의 수를 일치 시켜야 한다. 위의 예시에서 3 x 2 행렬과 2 x 3 행렬의 곱을 살펴보았다. 가운데 차원의 수가 2로 같은 것을 알 수 있다. 그래서 행렬의 곱셈이 가능한 것이다. 행렬의 곱셈은 꼭 차원의 수가 같아야지만 할 수 있는 것은 아니다. 차원의 수가 달라도 행렬의 곱셈이 가능하다.

In [12]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([7, 8])

np.dot(A, B)

array([23, 53, 83])

# 3.3.3 신경망에서의 행렬곱

그럼 이제 넘파이 행렬을 써서 신경망을 구현해보자. 아래 그림을 코드로 구현해 본다.

<p align="center"><img src="imgs/3-14.png" width=700></p>

In [15]:
X = np.array([1, 2])
print(X.shape)

W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)

Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[ 5 11 17]


np.dot 함수를 사용하지 않으면, Y의 원소를 하나하나 다 따져봐야 한다. np.dot을 사용하면 Y의 원소가 100개이든, 1000개이든 한 번에 계산이 가능하다.